const express = require('express');
const path = require('path');
const fs = require('fs');

// Load environment variables natively if .env exists
if (fs.existsSync('.env')) {
  fs.readFileSync('.env', 'utf-8')
    .split('\n')
    .forEach(line => {
      const trimmed = line.trim();
      if (trimmed && !trimmed.startsWith('#')) {
        const [key, ...val] = trimmed.split('=');
        if (key && val.length) {
          process.env[key.trim()] = val.join('=').trim().replace(/^["']|["']$/g, '');
        }
      }
    });
}

const app = express();
const PORT = process.env.PORT || 3000;

// Middleware
app.use((req, res, next) => {
  res.header('Access-Control-Allow-Origin', '*');
  res.header('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept');
  next();
});
app.use(express.json());
app.use(express.static(path.join(__dirname, 'public')));

/**
 * Validates and parses user input:
 * Checks for valid Facebook domains, profile URL patterns, numeric IDs, and usernames.
 */
function parseFacebookInput(input) {
  if (!input || typeof input !== 'string') {
    return { error: 'Please enter a Facebook Profile ID, Username, or Link.' };
  }
  const cleanInput = input.trim();
  if (!cleanInput) {
    return { error: 'Input cannot be empty.' };
  }

  // 1. Check if input is a pure numeric ID
  if (/^\d+$/.test(cleanInput)) {
    if (cleanInput.length > 25) {
      return { error: 'Numeric ID is too long to be a valid Facebook ID.' };
    }
    return { type: 'numeric_id', value: cleanInput };
  }

  // 2. Check if input looks like a URL
  if (/^https?:\/\/|www\.|\.com|\.net|\.org|\.me/i.test(cleanInput) || cleanInput.includes('/')) {
    try {
      let urlString = cleanInput;
      if (!/^https?:\/\//i.test(urlString)) {
        urlString = 'https://' + urlString;
      }
      const parsedUrl = new URL(urlString);
      const host = parsedUrl.hostname.toLowerCase();

      // Check if host is an allowed Facebook domain
      const fbDomains = ['facebook.com', 'fb.com', 'fb.me', 'fbcdn.net'];
      const isFbDomain = fbDomains.some(d => host === d || host.endsWith('.' + d));

      if (!isFbDomain) {
        return { 
          error: `"${host}" is not a recognized Facebook domain. Please enter a valid Facebook link (e.g. facebook.com/username).` 
        };
      }

      // Direct CDN image URL
      if (host.includes('fbcdn.net') || parsedUrl.pathname.includes('/v/t39.') || parsedUrl.pathname.includes('/v/t1.')) {
        return { type: 'cdn_url', value: cleanInput };
      }

      // Mobile share redirect link (e.g. facebook.com/share/1EMhdXTEaV/)
      if (parsedUrl.pathname.startsWith('/share/')) {
        return { type: 'share_url', value: urlString };
      }

      // Check for non-profile URLs on Facebook (groups, watch, marketplace, gaming, events)
      const segments = parsedUrl.pathname.split('/').filter(Boolean);
      const nonProfileKeywords = ['groups', 'events', 'gaming', 'watch', 'marketplace', 'login', 'recover', 'help', 'policies', 'ads', 'messages'];
      if (segments.length > 0 && nonProfileKeywords.includes(segments[0].toLowerCase())) {
        return {
          error: `The URL points to a Facebook "${segments[0]}" page, not an individual user profile. Please provide a direct Profile link or ID.`
        };
      }

      // Case A: profile.php?id=123456
      const idParam = parsedUrl.searchParams.get('id');
      if (idParam && /^\d+$/.test(idParam)) {
        return { type: 'numeric_id', value: idParam };
      }

      // Case B: /people/username-or-name/123456789
      const peopleMatch = parsedUrl.pathname.match(/\/people\/[^\/]+\/(\d+)/i);
      if (peopleMatch && peopleMatch[1]) {
        return { type: 'numeric_id', value: peopleMatch[1] };
      }

      // Case C: Path username like /zuck or /john.doe
      if (segments.length > 0) {
        const usernameCandidate = segments[0].replace(/[@\/]/g, '').trim();
        if (/^[a-zA-Z0-9.]{1,60}$/.test(usernameCandidate)) {
          return { type: 'username', value: usernameCandidate };
        }
      }

      return { error: 'Unable to detect a valid profile identifier from this Facebook link.' };
    } catch (err) {
      return { error: 'Malformed URL provided. Please verify the link format.' };
    }
  }

  // 3. Raw Username Validation
  const usernameCandidate = cleanInput.replace(/[@\/]/g, '').trim();
  if (!usernameCandidate) {
    return { error: 'Please enter a valid Facebook Profile ID or Username.' };
  }

  if (!/^[a-zA-Z0-9._-]{1,60}$/.test(usernameCandidate)) {
    return { 
      error: 'Invalid format. Facebook usernames and IDs only contain letters, numbers, dots, hyphens, or underscores.' 
    };
  }

  return { type: 'username', value: usernameCandidate };
}

/**
 * Core Dimension Upgrade Engine:
 * Facebook CDN links generated by mobile SSR contain:
 * ...&cstp=mx<MAX_SIZE>&ctp=p<PREVIEW_SIZE>... or ...&ctp=s<PREVIEW_SIZE>...
 * Whatever comes after ctp=p*** or ctp=s*** is replaced with what comes after mx***.
 */
function upgradeToMaxResolution(cdnUrl) {
  if (!cdnUrl || typeof cdnUrl !== 'string') {
    return { url: cdnUrl, upgraded: false, mxVal: null, origVal: null };
  }

  const mxMatch = cdnUrl.match(/[?&]cstp=mx([^&]+)/i);
  const ctpMatch = cdnUrl.match(/[?&]ctp=([a-z]?)([^&]+)/i);

  if (mxMatch && mxMatch[1] && ctpMatch) {
    const mxVal = mxMatch[1]; // e.g. "720x727"
    const prefix = ctpMatch[1] || 'p'; // "p" or "s"
    const origVal = ctpMatch[2]; // e.g. "240x240"

    const upgradedUrl = cdnUrl.replace(/([?&]ctp=[a-z]?)[^&]+/i, `$1${mxVal}`);
    const upgraded = origVal !== mxVal;

    return {
      url: upgradedUrl,
      upgraded,
      mxVal,
      origVal: `${prefix}${origVal}`,
    };
  }

  return { url: cdnUrl, upgraded: false, mxVal: null, origVal: null };
}

/**
 * Strategy 1 (Primary - Curl Ideology):
 * Curls the profile link with a mobile User-Agent to retrieve the SSR HTML,
 * validates whether the account exists or is disabled, and extracts the CDN profile picture preview link.
 */
async function curlAndExtractProfilePicture(target) {
  let profileUrl;
  if (/^https?:\/\//i.test(target)) {
    profileUrl = target;
  } else if (/^\d+$/.test(target)) {
    profileUrl = `https://www.facebook.com/profile.php?id=${target}`;
  } else {
    profileUrl = `https://www.facebook.com/${encodeURIComponent(target)}`;
  }

  try {
    const res = await fetch(profileUrl, {
      method: 'GET',
      redirect: 'follow',
      headers: {
        'User-Agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 16_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5 Mobile/15E148 Safari/604.1',
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
        'Accept-Language': 'en-US,en;q=0.9',
      },
    });

    if (res.status === 404) {
      return { notFound: true, message: 'Facebook returned HTTP 404 (Profile Not Found).' };
    }

    if (res.ok) {
      const html = await res.text();
      const lowerHtml = html.toLowerCase();

      // Check for Facebook's explicit "account does not exist" or "page unavailable" indicators
      const hasNotFoundMessage = 
        lowerHtml.includes("this page isn't available") ||
        lowerHtml.includes("this content isn't available") ||
        lowerHtml.includes("the link you followed may be broken") ||
        lowerHtml.includes("page not found");

      // Extract og:image
      let ogImage = null;
      const ogMatch = html.match(/<meta[^>]*property=["'](?:og:image|twitter:image)["'][^>]*content=["']([^"']+)["']/i) ||
                      html.match(/<meta[^>]*content=["']([^"']+)["'][^>]*property=["'](?:og:image|twitter:image)["']/i);
      if (ogMatch) {
        ogImage = ogMatch[1];
      }

      // If page shows "not available" and has no real photo, account does not exist
      if (hasNotFoundMessage && (!ogImage || ogImage.includes('lookaside') || ogImage.includes('static.xx.fbcdn'))) {
        return { notFound: true, message: 'This Facebook profile does not exist or has been deactivated/removed.' };
      }

      let ogTitle = null;
      const titleMatch = html.match(/<meta[^>]*property=["'](?:og:title|og:image:alt)["'][^>]*content=["']([^"']+)["']/i) ||
                         html.match(/<title>([^<]+)<\/title>/i);
      if (titleMatch) {
        ogTitle = titleMatch[1].replace(/\|\s*Facebook$/i, '').trim();
      }

      // Check if image points to Facebook CDN (scontent or fbcdn)
      if (ogImage && (ogImage.includes('fbcdn.net') || ogImage.includes('facebook.com') || ogImage.includes('fbsbx.com'))) {
        const rawPreviewUrl = ogImage.replace(/&amp;/g, '&');
        const upgradeInfo = upgradeToMaxResolution(rawPreviewUrl);
        const isSilhouette = rawPreviewUrl.includes('silhouette') || rawPreviewUrl.includes('static.xx.fbcdn');

        return {
          success: true,
          method: 'Direct Curl + mx Upgrade',
          imageUrl: upgradeInfo.url,
          previewUrl: rawPreviewUrl,
          mxResolution: upgradeInfo.mxVal,
          originalResolution: upgradeInfo.origVal,
          isUpgraded: upgradeInfo.upgraded,
          name: ogTitle || null,
          isSilhouette,
        };
      }

      // Fallback inside curled HTML: find any scontent img tag
      const scontentMatch = html.match(/https:\/\/[^"'\s<>\\]*scontent[^"'\s<>\\]*/i);
      if (scontentMatch) {
        const rawPreviewUrl = scontentMatch[0].replace(/&amp;/g, '&');
        const upgradeInfo = upgradeToMaxResolution(rawPreviewUrl);
        return {
          success: true,
          method: 'Direct Curl (HTML Regex) + mx Upgrade',
          imageUrl: upgradeInfo.url,
          previewUrl: rawPreviewUrl,
          mxResolution: upgradeInfo.mxVal,
          originalResolution: upgradeInfo.origVal,
          isUpgraded: upgradeInfo.upgraded,
          name: ogTitle || null,
          isSilhouette: rawPreviewUrl.includes('silhouette'),
        };
      }

      // If no image was found at all and title is generic "Facebook"
      if (!ogImage && (!ogTitle || ogTitle === 'Facebook')) {
        return { notFound: true, message: 'Facebook profile not found.' };
      }
    }
  } catch (err) {
    console.warn(`Curl extraction failed: ${err.message}`);
  }

  return null;
}

/**
 * Strategy 2: Graph API Fallback (with or without access token)
 */
async function fetchViaGraphApi(idOrUsername, type = 'large', accessToken = null) {
  const token = accessToken || process.env.FB_ACCESS_TOKEN || '';
  let apiUrl = `https://graph.facebook.com/${encodeURIComponent(idOrUsername)}/picture?type=${type}&redirect=false`;
  if (token) {
    apiUrl += `&access_token=${encodeURIComponent(token)}`;
  }

  try {
    const res = await fetch(apiUrl, {
      headers: {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
      },
    });

    const data = await res.json();
    if (!res.ok || data.error) {
      if (data.error && (data.error.code === 100 || data.error.code === 803 || data.error.message?.includes('does not exist'))) {
        return { notFound: true, error: data.error.message };
      }
      return null;
    }

    if (data && data.data && data.data.url) {
      const upgradeInfo = upgradeToMaxResolution(data.data.url);
      return {
        success: true,
        method: 'Graph API',
        imageUrl: upgradeInfo.url,
        previewUrl: data.data.url,
        mxResolution: upgradeInfo.mxVal,
        originalResolution: upgradeInfo.origVal,
        isUpgraded: upgradeInfo.upgraded,
        isSilhouette: data.data.is_silhouette || false,
      };
    }
  } catch (err) {
    console.warn(`Graph API JSON query failed: ${err.message}`);
  }

  // Follow redirect directly
  try {
    let redirectUrl = `https://graph.facebook.com/${encodeURIComponent(idOrUsername)}/picture?type=${type}`;
    if (token) {
      redirectUrl += `&access_token=${encodeURIComponent(token)}`;
    }
    const redirectRes = await fetch(redirectUrl, {
      method: 'GET',
      redirect: 'manual',
      headers: {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
      },
    });

    const location = redirectRes.headers.get('location');
    if (location && location.includes('fbcdn.net')) {
      const upgradeInfo = upgradeToMaxResolution(location);
      return {
        success: true,
        method: 'Graph API Redirect',
        imageUrl: upgradeInfo.url,
        previewUrl: location,
        mxResolution: upgradeInfo.mxVal,
        originalResolution: upgradeInfo.origVal,
        isUpgraded: upgradeInfo.upgraded,
        isSilhouette: location.includes('silhouette') || location.includes('generic'),
      };
    }
  } catch (err) {
    console.warn(`Graph API Redirect query failed: ${err.message}`);
  }

  return null;
}

/**
 * API Route: Get Profile Picture
 */
app.post('/api/get-profile-picture', async (req, res) => {
  const { input, size = 'large', customToken } = req.body;

  const parsed = parseFacebookInput(input);
  if (parsed.error) {
    return res.status(400).json({ success: false, error: parsed.error });
  }

  const target = parsed.value;

  // Handle direct CDN URL input
  if (parsed.type === 'cdn_url') {
    const upgradeInfo = upgradeToMaxResolution(parsed.value);
    const proxyDownloadUrl = `/api/download?url=${encodeURIComponent(upgradeInfo.url)}&id=cdn_photo`;
    return res.json({
      success: true,
      target: 'Direct CDN Photo',
      targetType: 'cdn_url',
      imageUrl: upgradeInfo.url,
      previewUrl: parsed.value,
      mxResolution: upgradeInfo.mxVal,
      originalResolution: upgradeInfo.origVal,
      isUpgraded: upgradeInfo.upgraded,
      proxyDownloadUrl,
      name: 'Facebook Photo',
      method: 'Direct CDN + mx Upgrade',
      isSilhouette: false,
      info: upgradeInfo.upgraded
        ? `Replaced preview crop ${upgradeInfo.origVal} with max resolution ${upgradeInfo.mxVal}.`
        : 'Photo retrieved successfully.',
    });
  }

  let result = null;

  // 1. Primary Strategy: Curl the profile directly
  const curlResult = await curlAndExtractProfilePicture(target);
  if (curlResult && curlResult.success) {
    result = curlResult;
  }

  // 2. Fallback to Graph API if curl didn't find image or returned silhouette
  if (!result || result.isSilhouette) {
    const graphResult = await fetchViaGraphApi(target, size, customToken);
    if (graphResult && graphResult.success && !graphResult.isSilhouette) {
      result = graphResult;
    } else if (!result && graphResult && graphResult.success) {
      result = graphResult;
    } else if (curlResult?.notFound && graphResult?.notFound) {
      // Both confirmed account does not exist
      return res.status(404).json({
        success: false,
        error: `Facebook account "@${target}" does not exist, has been deleted, or is deactivated.`
      });
    }
  }

  // 3. If account was not found or picture could not be extracted, return clean 404 error
  if (!result || !result.imageUrl) {
    return res.status(404).json({
      success: false,
      error: `Could not find a Facebook profile or extract a profile picture for "${target}". Please check that the account exists and is publicly accessible.`
    });
  }

  // Prepare download proxy URL
  const proxyDownloadUrl = `/api/download?url=${encodeURIComponent(result.imageUrl)}&id=${encodeURIComponent(target)}`;

  return res.json({
    success: true,
    target,
    targetType: parsed.type,
    imageUrl: result.imageUrl,
    previewUrl: result.previewUrl || result.imageUrl,
    mxResolution: result.mxResolution || null,
    originalResolution: result.originalResolution || null,
    isUpgraded: !!result.isUpgraded,
    proxyDownloadUrl,
    name: result.name || null,
    method: result.method,
    isSilhouette: !!result.isSilhouette,
    info: result.isSilhouette
      ? 'A placeholder silhouette was returned by Facebook. The profile may have strict privacy controls, Profile Picture Guard, or require a Graph API Access Token.'
      : 'Profile picture retrieved successfully.',
  });
});

/**
 * API Route: Download Image Proxy (Bypasses CORS and forces file download)
 */
app.get('/api/download', async (req, res) => {
  const { url, id = 'fb-profile' } = req.query;

  if (!url) {
    return res.status(400).send('Missing image URL parameter.');
  }

  try {
    const parsedUrl = new URL(url);
    const allowedHosts = ['fbcdn.net', 'facebook.com', 'akamaihd.net', 'fbsbx.com'];
    const isAllowed = allowedHosts.some(host => parsedUrl.hostname.endsWith(host));
    if (!isAllowed) {
      return res.status(403).send('Forbidden: URL must be from Facebook CDN.');
    }

    const imageResponse = await fetch(url, {
      headers: {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
      },
    });

    if (!imageResponse.ok) {
      return res.status(imageResponse.status).send('Failed to fetch image from source.');
    }

    const contentType = imageResponse.headers.get('content-type') || 'image/jpeg';
    const filename = `facebook_profile_${id.replace(/[^a-zA-Z0-9_-]/g, '_')}.jpg`;

    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
    res.setHeader('Content-Type', contentType);

    const arrayBuffer = await imageResponse.arrayBuffer();
    const buffer = Buffer.from(arrayBuffer);
    res.send(buffer);
  } catch (err) {
    console.error('Download proxy error:', err);
    res.status(500).send('Internal error downloading the image.');
  }
});

// Health check
app.get('/api/health', (req, res) => {
  res.json({ status: 'ok', time: new Date().toISOString() });
});

app.listen(PORT, () => {
  console.log(`Facebook Profile Picture Downloader running at http://localhost:${PORT}`);
});
